name: Trigger Sync to App

on:
push:
branches:
- main

jobs:
trigger:
runs-on: ubuntu-latest
steps:
- name: Send repository_dispatch to App
run: |
curl -X POST https://api.github.com/repos/OzikPutraJarwo/App/dispatches 
-H "Accept: application/vnd.github+json" 
-H "Authorization: token ${{ secrets.REPO_B_TOKEN }}" 
-d '{"event_type":"sync-advanta"}'